// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9mLMTo7d-DKGa45I9Z29l7ZMvuPfLt8U',
    appId: '1:308687130467:web:3e511e2da94c94608bcd56',
    messagingSenderId: '308687130467',
    projectId: 'beebuy-8d00b',
    authDomain: 'beebuy-8d00b.firebaseapp.com',
    storageBucket: 'beebuy-8d00b.appspot.com',
    measurementId: 'G-J2L358R5L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxMA8JH-G7SdSCWXQhPfwGvXgHD87RU0',
    appId: '1:308687130467:android:1d5f51e08ceb5e6d8bcd56',
    messagingSenderId: '308687130467',
    projectId: 'beebuy-8d00b',
    storageBucket: 'beebuy-8d00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGcrkYIkLKMZC1n0ov9pCbmJUEAt1UZ5A',
    appId: '1:308687130467:ios:c82ec08a9657064c8bcd56',
    messagingSenderId: '308687130467',
    projectId: 'beebuy-8d00b',
    storageBucket: 'beebuy-8d00b.appspot.com',
    iosClientId: '308687130467-acs8q5onbln88pfdtf84sli1bobvhu7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGcrkYIkLKMZC1n0ov9pCbmJUEAt1UZ5A',
    appId: '1:308687130467:ios:c82ec08a9657064c8bcd56',
    messagingSenderId: '308687130467',
    projectId: 'beebuy-8d00b',
    storageBucket: 'beebuy-8d00b.appspot.com',
    iosClientId: '308687130467-acs8q5onbln88pfdtf84sli1bobvhu7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );
}
